chisq.test(GKR$age,GKR$Dalc)
cor(GKR$age,GKR$Dalc,use="complete.obs",method=c("pearson"))
cor(GKR$famrel,GKR$Walc,use="complete.obs",method=c("pearson"))
reg1<- lm(GKR$age~GKR$Dalc)
plot(GKR$age~GKR$Dalc)
abline(reg1)
anova(reg1)
chisq.test(GKR$age,GKR$G1)
cor(GKR$age,GKR$G1,use="complete.obs",method=c("pearson"))
reg2<- lm(GKR$age~GKR$G1)
plot(GKR$age~GKR$G1)
abline(reg2)
anova(reg2)
chisq.test(GKR$age,GKR$Dalc)
cor(GKR$age,GKR$Dalc,use="complete.obs",method=c("pearson"))
reg3<- lm(GKR$age~GKR$Dalc)
plot(GKR$age~GKR$Dalc)
abline(reg3)
anova(reg3)
