library(readr)
Goteti <- read_csv("~/student-por.csv")
View(student_por)
summary(Goteti)
install.packages("arules")
install.packages("arulesViz")
na.rm=TRUE
na.NA=TRUE
library(arules)
rules<- lapply( student_por, as.factor)
St.all <- apriori(St)
hist(S)
is.numeric(S)
is.factor(S)
as.factor(S)
sort(S)
library(magrittr)
inspect(St.all)
summary(s)
